name: micro-service

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Setup action
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'

      - name: api-gateway
        run: |
          cd api-gateway
          go mod tidy
          go mod verify
      
      - name: Run Test
        run: |
          go test -v -cover ./...
    